### ISSUE TITLE
Rqt can't subscribe and publish controller topics.

### ISSUE THREAD

**Issue by ban-masa** [ros-naoqi/nao_virtual#12] opened 2015-11-08 22:23 UTC
I tried to control nao with the joint_trajectory_controller of rqt.
However, rqt can't subscribe and publish controller topics of nao_gazebo_plugin_H25.launch.
In version 0.0.5, the launch file fails to load controllers.
In version 0.0.4, the controllers' names are not suitable for rqt.
Rqt expects ```namespace = /path/to/controller/manager, controller_name = foo", if the published controller is "/path/to/foo```
However nao_gazebo_plugin outputs ```namespcae = /nao_dcm, controller_name = /nao_dcm/hoge_controller```

**Comment by keulYSMB** [comment] 2015-11-16 13:58
Hi,
You're right that's something that need to be fixed in the future. Does that prevent you to use rqt to send command or interact with the controllers ?
What is your use case ? and what rqt plugins are you using ?

What you should be able to do with this package:
Controller Manager rqt plugin: you can detect load and unload controllers
Message Publisher topic:
* Publish command to position controllers:<br> 
** add a controller command topic (e.g. /nao_dcm/Head_controller/command)<br>
** publish a std_msgs/Float64 message (command in radians)

* Publish comand to trajectory controller:<br> 
**You cannot publish this using rqt, you need to use the action server to send trajectories.

**Comment by keulYSMB** [comment] 2016-01-24 00:34
@ban-masa I was not able to reproduce your issue.
Did you try to run:
```
rosrun rqt_joint_trajectory_controller rqt_joint_trajectory_controller
```
It seems that rqt is able to recognize, enable and send commands to controllers

**Comment by ban-masa** [comment] 2016-01-24 02:59
I forgot to pull this commit(https://github.com/ros-naoqi/nao_robot/commit/f8eeae0).
After I pulled this commit, I can control nao with the joint_trajectory_controller of rqt.
I am sorry for the delay in my response, and thank you for your cooperation.

**Comment by keulYSMB** [comment] 2016-01-24 03:00
No worries, glad it works for you now

**Closed by keulYSMB** 2016-01-24 03:00 UTC
